# Training process
batch_size: 64
optimizer: 'adam'
learning_rate: 1e-4

# Network parameters
decoder_hidden_dim: 512
decoder_num_hidden_layers: 3
decoder_fc_dim: 128

encoder_hidden_sizes: [512, 512, 300]


num_labels: 101

