# Training process
batch_size: 16
optimizer: 'adam'
learning_rate: 1e-4

# Network parameters

performance_train_max_items: 1000

model:
    encoder_fc_dim1: 256
    encoder_fc_dim2: 256
    encoder_out_dim: 128

    decoder_hidden_dim: 512
    decoder_num_hidden_layers: 1
    decoder_fc_dim: 256

    num_labels: 101
